_wandb:
    value:
        cli_version: 0.26.1
        e:
            7vbb1fmm21b3i2w8bzc5nmw7tu85vkfs:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    macModel: Mac17,2
                    memoryGb: 16
                    name: Apple M5
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                args:
                    - -net
                    - VGG16
                    - -dataset
                    - PinsFaceRecognition
                    - -classes
                    - "105"
                    - -device
                    - mps
                    - -method
                    - zsmgm
                    - -forget_class
                    - "1"
                    - -weight_path
                    - checkpoints/VGG16PinsFaceRecognition.pth
                    - -data_root
                    - /Users/briancf/Developer/repos/Unlearning/datasets/105_classes_pins_dataset
                    - -seed
                    - "0"
                    - -zsmgm_config_path
                    - /Users/briancf/Developer/repos/Information-Theoretic-Unlearning/results/tuning_zsmgm/zsmgm_full_class_PinsFaceRecognition_VGG16_forget-1_seed-0/best_config.json
                codePath: src/forget_full_class_main.py
                codePathLocal: src/forget_full_class_main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994610155520"
                        used: "313232830464"
                email: canchola.brian@gmail.com
                executable: /Users/briancf/Developer/repos/Information-Theoretic-Unlearning/.venv/bin/python
                git:
                    commit: c96761408b4997381c2feab4fbe613aa4c1f2b12
                    remote: https://github.com/jwf40/Information-Theoretic-Unlearning.git
                host: Brians-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/briancf/Developer/repos/Information-Theoretic-Unlearning/src/forget_full_class_main.py
                python: CPython 3.12.9
                root: /Users/briancf/Developer/repos/Information-Theoretic-Unlearning
                startedAt: "2026-05-01T06:49:00.557274Z"
                writerId: 7vbb1fmm21b3i2w8bzc5nmw7tu85vkfs
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.26.1
            "6": 5.7.0
            "12": 0.26.1
            "13": darwin-arm64
dataset:
    value: PinsFaceRecognition
device:
    value: mps
forget_class:
    value: "1"
method:
    value: zsmgm
net:
    value: VGG16
seed:
    value: 0
zsmgm_epsilon:
    value: 0.04660383637790141
zsmgm_k_neighbors:
    value: 10
zsmgm_lambda_manifold:
    value: 9.215082688708396
zsmgm_learning_rate:
    value: 0.0016065643411417676
zsmgm_pgd_alpha:
    value: 0.00392156862745098
zsmgm_pgd_steps:
    value: 5
